spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bilsync
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true