version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - bilsync-sqldata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  bilsync-sqldata:
    external: true
